rofi = "~/.config/rofi"
Wallpapers = "~/Pictures/Wallpapers"
"picom.conf" = "~/.config/picom.conf"
bat = "~/.config/bat"
spicetify = "~/.config/spicetify"
i3 = "~/.config/i3"
nvim = "~/.config/nvim"
yazi = "~/.config/yazi"
".zshrc" = "~/.zshrc"
dunst = "~/.config/dunst"
"starship.toml" = "~/.config/starship.toml"
".wezterm.lua" = "~/.wezterm.lua"
polybar = "~/.config/polybar"
