polybar = "~/.config/polybar"
".zshrc" = "~/.zshrc"
nvim = "~/.config/nvim"
".scripts" = "~/.scripts"
Wallpapers = "~/Pictures/Wallpapers"
ghostty = "~/.config/ghostty"
config = "~/.i3/config"
"starship.toml" = "~/.config/starship.toml"
bat = "~/.config/bat"
".wezterm.lua" = "~/.wezterm.lua"
