"starship.toml" = "~/.config/starship.toml"
nvim = "~/.config/nvim"
".wezterm.lua" = "~/.wezterm.lua"
Wallpapers = "~/Pictures/Wallpapers"
".scripts" = "~/.scripts"
ghostty = "~/.config/ghostty"
".zshrc" = "~/.zshrc"
".i3" = "~/.i3"
polybar = "~/.config/polybar"
bat = "~/.config/bat"
rofi = "~/.config/rofi"
