Wallpapers = "~/Pictures/Wallpapers"
nvim = "~/.config/nvim"
rofi = "~/.config/rofi"
"picom.conf" = "~/.config/picom.conf"
i3 = "~/.config/i3"
"starship.toml" = "~/.config/starship.toml"
".zshrc" = "~/.zshrc"
".wezterm.lua" = "~/.wezterm.lua"
