rofi = "~/.config/rofi"
yazi = "~/.config/yazi"
nvim = "~/.config/nvim"
Wallpapers = "~/Pictures/Wallpapers"
".zshrc" = "~/.zshrc"
dunst = "~/.config/dunst"
"picom.conf" = "~/.config/picom.conf"
"starship.toml" = "~/.config/starship.toml"
".wezterm.lua" = "~/.wezterm.lua"
i3 = "~/.config/i3"
spicetify = "~/.config/spicetify"
polybar = "~/.config/polybar"
