nvim = "~/.config/nvim"
Wallpapers = "~/Pictures/Wallpapers"
".i3" = "~/.i3"
bat = "~/.config/bat"
".wezterm.lua" = "~/.wezterm.lua"
rofi = "~/.config/rofi"
conky = "~/.config/conky"
"starship.toml" = "~/.config/starship.toml"
polybar = "~/.config/polybar"
ghostty = "~/.config/ghostty"
".scripts" = "~/.scripts"
".zshrc" = "~/.zshrc"
