ghostty = "~/.config/ghostty"
bat = "~/.config/bat"
rofi = "~/.config/rofi"
"starship.toml" = "~/.config/starship.toml"
"tmux.conf" = "~/.config/tmux/tmux.conf"
".zshrc" = "~/.zshrc"
".wezterm.lua" = "~/.wezterm.lua"
"picom.conf" = "~/.config/picom.conf"
Wallpapers = "~/Pictures/Wallpapers"
polybar = "~/.config/polybar"
conky = "~/.config/conky"
nvim = "~/.config/nvim"
".scripts" = "~/.scripts"
".i3" = "~/.i3"
