Wallpapers = "~/Pictures/Wallpapers"
bat = "~/.config/bat"
"starship.toml" = "~/.config/starship.toml"
ghostty = "~/.config/ghostty"
".scripts" = "~/.scripts"
rofi = "~/.config/rofi"
polybar = "~/.config/polybar"
".zshrc" = "~/.zshrc"
"tmux.conf" = "~/.config/tmux/tmux.conf"
".wezterm.lua" = "~/.wezterm.lua"
conky = "~/.config/conky"
".i3" = "~/.i3"
