polybar = "~/.config/polybar"
bat = "~/.config/bat"
ghostty = "~/.config/ghostty"
".zshrc" = "~/.zshrc"
Wallpapers = "~/Pictures/Wallpapers"
nvim = "~/.config/nvim"
rofi = "~/.config/rofi"
conky = "~/.config/conky"
"starship.toml" = "~/.config/starship.toml"
"tmux.conf" = "~/.config/tmux/tmux.conf"
".scripts" = "~/.scripts"
".wezterm.lua" = "~/.wezterm.lua"
".i3" = "~/.i3"
