"tmux.conf" = "~/.config/tmux/tmux.conf"
".zshrc" = "~/.zshrc"
".wezterm.lua" = "~/.wezterm.lua"
ghostty = "~/.config/ghostty"
conky = "~/.config/conky"
".i3" = "~/.i3"
nvim = "~/.config/nvim"
Wallpapers = "~/Pictures/Wallpapers"
"starship.toml" = "~/.config/starship.toml"
polybar = "~/.config/polybar"
bat = "~/.config/bat"
rofi = "~/.config/rofi"
".scripts" = "~/.scripts"
