polybar = "~/.config/polybar"
config = "~/.i3/config"
".wezterm.lua" = "~/.wezterm.lua"
nvim = "~/.config/nvim"
Wallpapers = "~/Pictures/Wallpapers"
"starship.toml" = "~/.config/starship.toml"
ghostty = "~/.config/ghostty"
".zshrc" = "~/.zshrc"
bat = "~/.config/bat"
