return {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    priority = 1000,
    opts = {
      transparent_background = false,
      terminal = false,
      integrations = {
        alpha = true,
        aerial = true,
        dap = true,
        dap_ui = true,
        mason = true,
        neotree = true,
        notify = true,
        nvimtree = false,
        semantic_tokens = true,
        symbols_outline = true,
        telescope = true,
        ts_rainbow = true,
        which_key = true,
      },
      color_overrides = {
        -- Carburetor
        mocha = {
          rosewater = "#ffd7d9",
          flamingo = "#ffb3b8",
          pink = "#ff7eb6",
          mauve = "#d4bbff",
          red = "#fa4d56",
          maroon = "#ff8389",
          peach = "#ff832b",
          yellow = "#fddc69",
          green = "#42be65",
          teal = "#3ddbd9",
          sky = "#82cfff",
          sapphire = "#78a9ff",
          blue = "#4589ff",
          lavender = "#be95ff",
          text = "#f4f4f4",
          subtext1 = "#e0e0e0",
          subtext0 = "#c6c6c6",
          overlay2 = "#a8a8a8",
          overlay1 = "#8d8d8d",
          overlay0 = "#6f6f6f",
          surface2 = "#525252",
          surface1 = "#393939",
          surface0 = "#262626",
          base = "#161616",
          mantle = "#0b0b0b",
          crust = "#000000",
        },
      },
    },
  },
}
